export const stylePropKeys: string[] = [
  'margin',
  'marginRight',
  'marginLeft',
  'marginTop',
  'marginBottom',
  'marginX',
  'marginY',
  'm',
  'mr',
  'ml',
  'mt',
  'mb',
  'mx',
  'my',

  'padding',
  'paddingRight',
  'paddingLeft',
  'paddingTop',
  'paddingBottom',
  'paddingX',
  'paddingY',
  'p',
  'pr',
  'pl',
  'pt',
  'pb',
  'px',
  'py',

  'backgroundColor',
  'bg',
  'color',
  'opacity',

  'fontFamily',
  'fontSize',
  'fontWeight',
  'lineHeight',
  'letterSpacing',
  'textAlign',
  'fontStyle',

  'width',
  'minWidth',
  'maxWidth',
  'w',
  'minW',
  'maxW',

  'height',
  'minHeight',
  'maxHeight',
  'h',
  'minH',
  'maxH',

  'size',
  'display',
  'verticalAlign',
  'overflow',
  'overflowX',
  'overflowX',

  'alignItems',
  'alignContent',
  'justifyItems',
  'justifyContent',
  'flexWrap',
  'flexDirection',
  'flex',
  'flexGrow',
  'flexShrink',
  'flexBasis',
  'justifySelf',
  'alignSelf',
  'order',
  'gap',

  'gridGap',
  'gridRowGap',
  'gridColumnGap',
  'gridColumn',
  'gridRow',
  'gridArea',
  'gridAutoRows',
  'gridAutoFlow',
  'gridAutoColumns',
  'gridTemplateRows',
  'gridTemplateColumns',
  'gridTemplateAreas',

  'background',
  'backgroundImage',
  'backgroundSize',
  'backgroundPosition',
  'backgroundRepeat',

  'border',
  'borderWidth',
  'borderStyle',
  'borderColor',
  'borderRadius',
  'borderTop',
  'borderTopWidth',
  'borderTopStyle',
  'borderTopColor',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderRight',
  'borderRightWidth',
  'borderRightStyle',
  'borderRightColor',
  'borderBottom',
  'borderBottomWidth',
  'borderBottomStyle',
  'borderBottomColor',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderLeft	',
  'borderLeftWidth',
  'borderLeftStyle',
  'borderLeftColor',
  'borderX	',
  'borderY',

  'position',
  'zIndex',
  'top',
  'bottom',
  'left',
  'right',
  'textShadow',
  'boxShadow',
  'shadow'
];

export const STYLE_PROP_TYPES = Object.freeze(
  Object.fromEntries(
    stylePropKeys.map(key => [
      key,
      { type: [Array, String, Number], default: null }
    ])
  )
);
